Repository christophechr/LeAREA, pull requests merged in 2023-12, with the labels that each got.

#2 Replace Backend by Fastify
  .github/workflows/main.yml
  .gitignore
  README.md
  area-expo/Dockerfile
  area-node/.env.exemple
  area-node/README.md
  area-node/package-lock.json
  area-node/package.json
  area-node/src/app.js
  area-node/src/controllers/auth.controller.js
  area-node/src/middlewares/exemple.middleware.js
  area-node/src/models/user.model.js
  area-node/src/routes/auth.route.js
  area-node/src/routes/index.js
  area-node/src/utils/jwt.utils.js
  area-react/Dockerfile
  compose.yml
  docs/Benchmark-Technologies-choice.pdf
  docs/CONTRIBUTE.md
  docs/technical-schems.pdf
Labels: enhancement

#6 Fix the github action to push on release only
  .github/workflows/main.yml
Labels: bug, enhancement

#9 Update the README & CONTRIBUTE
  README.md
  docs/CONTRIBUTE.md
Labels: documentation

#21 Add API Documentation
  area-node/OpenAPI.yaml
  area-node/src/actions/github.action.js
  area-node/src/config/actions.config.js
  area-node/src/config/triggers.config.js
  area-node/src/controllers/flows.controller.js
  area-node/src/controllers/github.controller.js
  area-node/src/routes/auth.route.js
  area-node/src/tasks/flows.task.js
  area-node/src/triggers/weather.trigger.js
Labels: documentation, bug-fix

#19 Update doc
  docs/Benchmark-Technologies-choice.pdf
Labels: documentation
