Repository christophechr/LeAREA, pull requests merged in 2024-01, with the labels that each got.

#33 ADD Google token end-user acquirement
  area-node/.env.exemple
  area-node/package.json
  area-node/src/actions/github.action.js
  area-node/src/app.js
  area-node/src/config/actions.config.js
  area-node/src/config/triggers.config.js
  area-node/src/controllers/flows.controller.js
  area-node/src/controllers/google.controller.js
  area-node/src/models/flow.model.js
  area-node/src/models/user.model.js
  area-node/src/public/images/github.png
  area-node/src/public/images/weather.png
  area-node/src/routes/flows.route.js
  area-node/src/routes/google.route.js
  area-node/src/routes/index.js
  area-node/src/tasks/flows.task.js
  area-react/src/App.js
  area-react/src/WorkflowPages/workflowpage.js
  area-react/src/loginPages/GithubPages/github.js
Labels: enhancement

#36 Mobile ci
  .github/workflows/mobile-ci.yml
Labels: enhancement

#39 About.json
  area-node/src/config/about.config.js
  area-node/src/controllers/about.controller.js
  area-node/src/routes/about.route.js
  area-node/src/routes/index.js
Labels: documentation

#40 [ADD] update API documentation
  area-node/OpenAPI.yaml
  area-node/README.md
  area-node/src/controllers/auth.controller.js
  area-node/src/controllers/flows.controller.js
  area-node/src/controllers/google.controller.js
  area-node/src/controllers/spotify.controller.js
  area-node/src/routes/google.route.js
Labels: documentation

#45 [BACKEND] Google fixes
  area-node/src/app.js
  area-node/src/config/google.init.js
  area-node/src/config/triggers.config.js
  area-node/src/controllers/flows.controller.js
  area-node/src/controllers/google.controller.js
  area-node/src/init/google.trigger.init.js
  area-node/src/init/index.js
  area-node/src/triggers/gmail.trigger.js
Labels: bug-fix

#54 Micrpayments
  area-node/README.md
  area-node/src/actions/http.action.js
  area-node/src/actions/index.js
  area-node/src/actions/micpmt.action.js
  area-node/src/config/actions.config.js
  area-node/src/config/triggers.config.js
  area-node/src/controllers/auth.controller.js
  area-node/src/models/user.model.js
  area-node/src/public/images/micropayment.webp
  area-node/src/triggers/index.js
  area-node/src/triggers/micpmt.trigger.js
  compose.yml
Labels: enhancement
